features:
  selected:
    - underwater
    - herd
    - momentum
    - volatility
  params:
    underwater: {}
    herd:
      window: 5
    momentum:
      window: 20
    volatility:
      window: 20

scaling:
  method: standard
